### ISSUE TITLE
如何清空播放列表

### ISSUE THREAD

**Issue by Request-timed-out** [dufu1991/simple-cloud-music#12]
rt，只有清除浏览器缓存这一条办法了吗

**Comment by Request-timed-out** [comment]
@dufu1991

**Comment by dufu1991** [comment]
重新播放一个歌单就会覆盖掉旧的列表，目前没有做清空播放列表的功能。

**Comment by Request-timed-out** [comment]
> 重新播放一个歌单就会覆盖掉旧的列表，目前没有做清空播放列表的功能。

ok非常感谢！另外网站的SSL证书是不是过期了，我最近作为pwa应用打开时地址栏显示红色的https和删除线，还隐藏不了（如果是安全https地址栏能隐藏），比较影响作为应用的沉浸式体验/捂脸/捂脸

**Comment by Request-timed-out** [comment]
刚才上电脑看 错误确实是证书无效

不过想起来前段时间收藏了一个帖子，也许大佬可以试试用这个网站 https://zerossl.com/ 免费签名SSL证书

**Comment by dufu1991** [comment]
已经重新部署了证书，阿里云也可以申请免费证书。

**Comment by dufu1991** [comment]
感谢提醒，请重新用域名使用。
