### ISSUE TITLE
iOS已修复PWA后台播放支持

### ISSUE THREAD

**Issue by eric1932** [dufu1991/simple-cloud-music#13]
https://www.qumuban.com/59755.html
https://twitter.com/othermaciej/status/1491500338305667072
https://medium.com/prototyped/what-we-learned-about-pwas-and-audio-playback-10a01c6aecbd

据说iOS 15.4已经修复了对PWA应用后台音乐播放的支持

经过测试 open.spotify.com 安装PWA可以在回到桌面后继续播放

也许可以考虑把这个功能给加回来

**Comment by dufu1991** [comment]
我用iOS16正式版试了一下，还是不行的，你说这个15.4是不是预览版？或者有些属性默认未开启，需要开发者选项去开启？

**Comment by eric1932** [comment]
https://user-images.githubusercontent.com/10938293/192683307-56fe664a-f291-490c-a0aa-effc4f305d87.mp4

换16.0又试了一次，我这边是可以后台播放的

另外一台15.4的手机也是一样可以的，都没有做啥额外设置

**Comment by eric1932** [comment]
如何 有说法么

**Comment by NameGTHuB** [comment]
> 我用iOS16正式版试了一下，还是不行的，你说这个15.4是不是预览版？或者有些属性默认未开启，需要开发者选项去开启？

PAW可以后台播放了吗？

**Comment by zdong22** [comment]
记得设置一下audio的title为歌曲名称，可以显示在锁屏界面上

**Comment by dufu1991** [comment]
> foobar404/wave

是移除还是引入？

**Comment by dufu1991** [comment]
> 移除即可发自我的荣耀手机-------- 原始邮件 --------发件人： dufu1991 ***@***.***>日期： 2023年5月24日周三 19:02收件人： dufu1991/simple-cloud-music ***@***.***>抄送： zdong22 ***@***.***>, Comment ***@***.***>主 题： Re: [dufu1991/simple-cloud-music] iOS已修复PWA后台播放支持 (Issue #13) foobar404/wave 是移除还是引入？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

感谢你的参与，刚刚想尝试一下，也更新后端api到最新版本，可能变得比较多，登录接口都不成功了，懒得搞了，这个issue我就关了，其他人可以参考尝试。
