### ISSUE TITLE
-462：请完成验证操作

### ISSUE THREAD

**Issue by Request-timed-out** [dufu1991/simple-cloud-music#14]
最近登录pwa应用总显示-462：请完成验证操作，点击 我知道了 以后也没有跳出验证码，同时不能听歌，这是什么情况？已禁用所有广告拦截插件。

**Comment by dufu1991** [comment]
尝试退出帐号重新登录。

**Comment by Request-timed-out** [comment]
@dufu1991 按现在这个机制的话是不是在游客状态下完全没办法听歌？

**Comment by dufu1991** [comment]
1 退出登录不要登录（会清除所有登录的缓存数据，相当于应用最开始的样子）。
2 是否允许游客模式听歌是跟随网易云接口的，按我之前用的时候部分歌曲是可以听的。

**Comment by Request-timed-out** [comment]
@dufu1991 还是不行。现在的情况是清除缓存后使用chrome无痕模式打开网站，不登录仍然提示-462，同时搜索结果不显示，歌单点开空白。网易云账号我一个月前刚注销，本来打算拿这个当主力结果碰上现在这个情况。

https://netease-music.fe-mm.com/ 这个也是调用网易云接口，目前还是可以用的。非常不喜欢的就是每次播完后都自动播放推荐歌单，导致每次都要手动清空列表，并且不能播放专辑。还是希望能用回简易云。

**Comment by Request-timed-out** [comment]
@dufu1991 还是不行。现在的情况是清除缓存后使用chrome无痕模式打开网站，不登录仍然提示-462，同时搜索结果不显示，歌单点开空白，手机电脑都一样。网易云账号我一个月前刚注销，本来打算拿这个当主力结果碰上现在这个情况。

https://netease-music.fe-mm.com/ 这个也是调用网易云接口，目前还是可以用的。非常不喜欢的就是每次播完后都自动播放推荐歌单，导致每次都要手动清空列表。还是希望能用回简易云。

**Comment by dufu1991** [comment]
我试了下清除所有缓存之后是正常的。不过经过你的提示，我增加个清除所有缓存的功能吧。

**Comment by Request-timed-out** [comment]
@dufu1991 问题依然存在，我已经切换了4台不同设备，在家人的设备上也尝试了也是如此，无论如何切换流量/无线、清除缓存、开关科学。我感觉基本能排除客户端的问题。不知道你有没有用v2ex，不如让上面的老哥在多地区分别测试一下使用情况看看？

**Comment by dufu1991** [comment]
我发了一个帖子，https://www.v2ex.com/t/888513。你关注一下别人的反馈。

**Comment by dufu1991** [comment]
我发了一个帖子，https://www.v2ex.com/t/888513。
你关注一下别人的反馈。

**Comment by Request-timed-out** [comment]
@dufu1991 看了一下大家，好像也是碰到同样的问题。。

**Comment by Request-timed-out** [comment]
@dufu1991 兄弟有空修下吧，没空就算了

**Comment by dufu1991** [comment]
playlist/catlist 接口报错。code: -462，message: "请完成验证操作"。
请到 https://github.com/Binaryify/NeteaseCloudMusicApi 提 issues。
