### ISSUE TITLE
iOS PWA 模式中右滑手势返回动画重复播放

### ISSUE THREAD

**Issue by cattail5** [dufu1991/simple-cloud-music#3]
比如从 “我喜欢的音乐” 右滑返回 “我的主页” 时会重复播放第二遍返回动画，很抱歉我并没有录制复现视频。不过点击左上角的返回按键时则只播放一遍动画，是正常的。

PWA 模式不能后台播放，有群友说是 iOS 的限制。这是个遗憾 😢 。

手机号登录似乎只支持 +86，我目前绑定的手机号是 GV 号 🤣 。不过既然支持多种登录方式，不支持 +1 也没有什么影响。

**Comment by dufu1991** [comment]
readme 里面已经说了，Safari 的右滑返回是系统级的，都会重载一下动画，无法解除，不影响使用。
