### ISSUE TITLE
私人FM相关问题

### ISSUE THREAD

**Issue by chartjin15** [dufu1991/simple-cloud-music#5]
你好开发者，非常感谢你制作了这款网易云第三方网页应用！

在使用这款应用的过程中，我发现在成功登录后，基本每次都会弹出以下弹窗：
- 502：[object Object]
- [object Object]：[object Object]
- undefined：未知错误

并且私人FM在绝大多数情况下也不可用，点按相关按钮框会弹窗：
- [object Object]：[object Object]

即使偶然成功开始播放，在私人FM播放过程中也出现了循环播放若干首歌的情况。

初步判定为应用通过相关API获取私人FM相关数据失败导致，但本人技术力不过关，无力修复。不知开发者能否尝试修复呢？

另给出一点小建议：在搜索界面及搜索结果界面中添加「专辑」栏并返回相关结果。按专辑搜索并顺序播放对于一部分本应用的使用者来说非常的有用。

再次感谢开发者为开发本应用付出的努力。

**Comment by dufu1991** [comment]
关于报错的问题，我这边试了几个账号都没问题，我也不能用你的账号看报错情况。只能猜测是账号数据的问题（新注册的账号易发），建议几个方式试一下：1.退出账号重新登录；2.用你身边其他人的账号试一下；3.清除浏览器所有缓存数据或换个浏览器试试。
关于专辑维度，考虑弄一下，下个版本。

**Comment by chartjin15** [comment]
这样吗，好的。
谢谢回复！
----- 原始邮件 -----
发件人：dufu1991 ***@***.***>
收件人：dufu1991/simple-cloud-music ***@***.***>
抄送人：木公卡尺 ***@***.***>,  Author ***@***.***>
主题：Re:_[dufu1991/simple-cloud-music]_私人FM相关问题_(Issue_#5)
日期：2021年11月09日 10点56分


关于报错的问题，我这边试了几个账号都没问题，我也不能用你的账号看报错情况。只能猜测是账号数据的问题（新注册的账号易发），建议几个方式试一下：1.退出账号重新登录；2.用你身边其他人的账号试一下；3.清除浏览器所有缓存数据或换个浏览器试试。

关于专辑维度，考虑弄一下，下个版本。

&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
