### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Germxu** [dufu1991/simple-cloud-music#8]
你好, 我想跑一下你的代码, 应该有些东西你没有上传? 
我跑不起来, 好像是依赖版本不对, 因为没有lock文件
希望可以一起维护一下

**Comment by dufu1991** [comment]
说一下你的详细步骤，我看看是什么问题。

**Comment by Germxu** [comment]
node-sass安装, cmake等问题

dufu1991 ***@***.***> 于2022年1月24日周一 19:24写道：

**Comment by dufu1991** [comment]
建议node和npm都升级到最新稳定版试试。这个我推测是node版本的问题。

**Comment by Germxu** [comment]
还是差一个json读取不能运行, 错误解决参考 https://www.cnblogs.com/shenfanzui/p/13322826.html
我跑起来了
