### ISSUE TITLE
拉取代码第一次启动报错，缺少依赖项

### ISSUE THREAD

**Issue by zdong22** [dufu1991/simple-cloud-music#9]
## 拉取代码后，npm i , npm run dev  。发现缺少依赖项

![error](https://user-images.githubusercontent.com/49530167/159108117-c0e0d0ca-a6f5-41a7-bd8e-0a673c793c1b.jpg)

## 解决办法:

1.  npm i @rollup/plugin-json -D
2.  修改rollup.config.js , 
```
import json from '@rollup/plugin-json'

      plugins: [
            json(),
      ]
```

3. npm run dev ，启动成功

**Comment by dufu1991** [comment]
我身边的人尝试启动好像没遇到，是不是某个依赖库的版本原因。不过还是非常感谢您的反馈。

**Comment by dufu1991** [comment]
thanks!

**Comment by GeekBerry** [comment]
`unexpected token (note that you need @rollup/plugin-json to import json files)`
在 package.json 里没有 `@rollup/plugin-json`
